version: 2

# set the version of Python and other tools
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

# build the documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  
# optionally declare the Python requirements required to build the docs
python:
  install:
    - requirements: docs/requirements.txt
